import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

input_img1=cv2.imread(r"C:\Users\bhoga\Downloads\Picture1.png")
input_img2=cv2.imread(r"C:\Users\bhoga\Downloads\Picture2.png")
input_img3=cv2.imread(r"C:\Users\bhoga\Downloads\Picture3.png")
input_img4=cv2.imread(r"C:\Users\bhoga\Downloads\Picture4.png")
input_img5=cv2.imread(r"C:\Users\bhoga\Downloads\Picture5.png")
gray_1=cv2.cvtColor(input_img1,cv2.COLOR_BGR2GRAY)
gray_2=cv2.cvtColor(input_img2,cv2.COLOR_BGR2GRAY)
gray_3=cv2.cvtColor(input_img3,cv2.COLOR_BGR2GRAY)
gray_4=cv2.cvtColor(input_img4,cv2.COLOR_BGR2GRAY)
gray_5=cv2.cvtColor(input_img5,cv2.COLOR_BGR2GRAY)
def generate_histogram(image):
    histogram=cv2.calcHist([image],[0],None,[256],[0,256])
    return histogram
hist1=generate_histogram(gray_1)
hist2=generate_histogram(gray_2)
hist3=generate_histogram(gray_3)
hist4=generate_histogram(gray_4)
hist5=generate_histogram(gray_5)
def input_plots(gray,hist):
    intensity=np.arange(256)
    plt.figure(figsize=(6,4))
    plt.subplot(1,2,1)
    plt.imshow(gray,cmap='gray')
    plt.title("Input image")
    plt.axis('off')
    #hist plot for same image
    plt.subplot(1,2,2)
    plt.bar(intensity,hist)
    plt.title("Image histogram")
    plt.xlim([0,255])
    plt.xlabel("Intensity")
    plt.ylabel("Number of pixels")
    plt.tight_layout()
    return plt.show()
plot1=input_plots(gray_1,hist1)
plot2=input_plots(gray_2,hist2)
plot3=input_plots(gray_3,hist3)
plot4=input_plots(gray_4,hist4)
plot5=input_plots(gray_5,hist5)

def perform_hist_equlization(image):
    equalization=cv2.equalizeHist(image)
    return equalization
eql_hist1=perform_hist_equlization(gray_1)
eql_hist2=perform_hist_equlization(gray_2)
eql_hist3=perform_hist_equlization(gray_3)
eql_hist4=perform_hist_equlization(gray_4)
eql_hist5=perform_hist_equlization(gray_5)
hist6=generate_histogram(eql_hist1)
hist7=generate_histogram(eql_hist2)
hist8=generate_histogram(eql_hist3)
hist9=generate_histogram(eql_hist4)
hist10=generate_histogram(eql_hist5)

def plot_eql_hist(image,hist,eqval_image,eqlhist):
    intensity=np.arange(256)
    plt.figure(figsize=(8,6))
    plt.subplot(2,2,1)
    plt.imshow(image,cmap='gray')
    plt.title("Original image")
    plt.axis('off')
    plt.subplot(2,2,2)
    plt.bar(intensity,hist)
    plt.xlim([0,255])
    plt.xlabel("Intensity of pixels ")
    plt.ylabel('Number of pixels')
    plt.title("Original image histogram")
    plt.subplot(2,2,3)
    plt.imshow(eqval_image,cmap='gray')
    plt.title("Equalized image")
    plt.axis('off')
    plt.subplot(2,2,4)
    plt.bar(intensity,eqlhist)
    plt.xlabel("equalized inmage")
    plt.ylabel("Intensity")
    plt.title("Histogram of equalized inmage")
    plt.tight_layout()
    return plt.show()
img1=plot_eql_hist(gray_1,hist1,eql_hist1,hist6)
img2=plot_eql_hist(gray_2,hist2,eql_hist2,hist7)
img3=plot_eql_hist(gray_3,hist3,eql_hist3,hist8)
img4=plot_eql_hist(gray_4,hist4,eql_hist4,hist9)
img5=plot_eql_hist(gray_5,hist5,eql_hist5,hist10)
#matching images
from skimage.exposure import match_histograms

matched_img1=match_histograms(gray_1,eql_hist1)
matched_img2=match_histograms(gray_2,eql_hist1)
matched_img3=match_histograms(gray_3,eql_hist1)
matched_img4=match_histograms(gray_4,eql_hist1)
matched_img5=match_histograms(gray_5,eql_hist1)
m_img1=np.uint8(matched_img1)
m_img2=np.uint8(matched_img2)
m_img3=np.uint8(matched_img3)
m_img4=np.uint8(matched_img4)
m_img5=np.uint8(matched_img5)
m_hist1=generate_histogram(m_img1)
m_hist2=generate_histogram(m_img2)
m_hist3=generate_histogram(m_img3)
m_hist4=generate_histogram(m_img4)
m_hist5=generate_histogram(m_img5)


def plot_match_histogram(image,r_image,hist,r_hist,m_image,m_hist):
    intensity=np.arange(256)
    plt.figure(figsize=(8,6))
    plt.subplot(3,2,1)
    plt.imshow(image,cmap='gray')
    plt.title("Original image")
    plt.axis('off')
    plt.subplot(3,2,2)
    plt.bar(intensity,hist)
    plt.xlabel("Pixel range")
    plt.ylabel("Frequency")
    plt.title("Hist plaot of original image")
    plt.xlim([0,256])
    plt.subplot(3,2,3)
    plt.imshow(r_image,cmap='gray')
    plt.title("reference image")
    plt.axis('off')
    plt.subplot(3,2,4)
    plt.bar(intensity,r_hist)
    plt.xlabel("Pixel range")
    plt.ylabel("Frequency")
    plt.title("Hist plaot of reference image")
    plt.xlim([0,256])
    plt.subplot(3,2,5)
    plt.imshow(m_image,cmap='gray')
    plt.title("matched image")
    plt.axis('off')
    plt.subplot(3,2,6)
    plt.bar(intensity,m_hist)
    plt.xlabel("Pixel range")
    plt.ylabel("Frequency")
    plt.title("Hist plaot of matched image")
    plt.xlim([0,256])
    plt.tight_layout()
    return plt.show()
plt1=plot_match_histogram(gray_1,eql_hist1,hist1,hist6,m_img1,m_hist1)
plt2=plot_match_histogram(gray_2,eql_hist1,hist2,hist6,m_img2,m_hist2)
plt3=plot_match_histogram(gray_3,eql_hist1,hist3,hist6,m_img3,m_hist3)
plt4=plot_match_histogram(gray_4,eql_hist1,hist4,hist6,m_img4,m_hist4)
plt5=plot_match_histogram(gray_5,eql_hist1,hist5,hist6,m_img5,m_hist5)
        
        
    