from skimage.exposure import match_histograms

matched_img1=match_histograms(gray_1,eql_hist1)
matched_img2=match_histograms(gray_2,eql_hist1)
matched_img3=match_histograms(gray_3,eql_hist1)
matched_img4=match_histograms(gray_4,eql_hist1)
matched_img5=match_histograms(gray_5,eql_hist1)
m_img1=np.uint8(matched_img1)
m_img2=np.uint8(matched_img2)
m_img3=np.uint8(matched_img3)
m_img4=np.uint8(matched_img4)
m_img5=np.uint8(matched_img5)
m_hist1=generate_histogram(m_img1)
m_hist2=generate_histogram(m_img2)
m_hist3=generate_histogram(m_img3)
m_hist4=generate_histogram(m_img4)
m_hist5=generate_histogram(m_img5)


def plot_match_histogram(image,r_image,hist,r_hist,m_image,m_hist):
    intensity=np.arange(256)
    plt.figure(figsize=(8,6))
    plt.subplot(3,2,1)
    plt.imshow(image,cmap='gray')
    plt.title("Original image")
    plt.axis('off')
    plt.subplot(3,2,2)
    plt.bar(intensity,hist)
    plt.xlabel("Pixel range")
    plt.ylabel("Frequency")
    plt.title("Hist plaot of original image")
    plt.xlim([0,256])
    plt.subplot(3,2,3)
    plt.imshow(r_image,cmap='gray')
    plt.title("reference image")
    plt.axis('off')
    plt.subplot(3,2,4)
    plt.bar(intensity,r_hist)
    plt.xlabel("Pixel range")
    plt.ylabel("Frequency")
    plt.title("Hist plaot of reference image")
    plt.xlim([0,256])
    plt.subplot(3,2,5)
    plt.imshow(m_image,cmap='gray')
    plt.title("matched image")
    plt.axis('off')
    plt.subplot(3,2,6)
    plt.bar(intensity,m_hist)
    plt.xlabel("Pixel range")
    plt.ylabel("Frequency")
    plt.title("Hist plaot of matched image")
    plt.xlim([0,256])
    plt.tight_layout()
    return plt.show()
plt1=plot_match_histogram(gray_1,eql_hist1,hist1,hist6,m_img1,m_hist1)
plt2=plot_match_histogram(gray_2,eql_hist1,hist2,hist6,m_img2,m_hist2)
plt3=plot_match_histogram(gray_3,eql_hist1,hist3,hist6,m_img3,m_hist3)
plt4=plot_match_histogram(gray_4,eql_hist1,hist4,hist6,m_img4,m_hist4)
plt5=plot_match_histogram(gray_5,eql_hist1,hist5,hist6,m_img5,m_hist5)
        
        
    